version: "3.8"
services:
  postgres:
    image: postgres:15
    env_file: .env.example
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    depends_on:
      - postgres
      - redis
    env_file: .env.example
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./frontend:/app/frontend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: ./backend
    depends_on:
      - redis
      - postgres
    env_file: .env.example
    command: celery -A app.worker.celery_app worker --loglevel=info -Q imports,webhooks

volumes:
  pgdata:
